apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-web
  template:
    metadata:
      labels:
        app: node-web
    spec:
      containers:
        - name: node-web
          image: my-node-app:BUILD_TAG
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: "redis"

